name = "Thaumiel25"
author = "tokebe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc477b45f510a23866afe28c70a6dc2562b4084bb0b0ea9957fc4382e07c1ee6"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
