name = "Thaumiel25"
author = "tokebe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0389494d30a607b79d0696c3c18268a12c64ba7d0c3540aaeb4e5f368ed42572"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
