name = "Thaumiel25"
author = "tokebe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8cc1b5e9e2c49799a401559f405bdcf11ffda8ceb244763771678e71fed1f72"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
