name = "Thaumiel25"
author = "tokebe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48e99c1bff9a1c8200a7ce6599aa1db75e890ee0b7e042652794e62dbd22a6c4"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
