name = "Thaumiel25"
author = "tokebe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c4cd7e925ce3b67af90254df94620c5160137d6eb520b1872dee0c979371067"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
